services:
  # ─── DATABASES ───────────────────────────────────────────
  patient-db:
    image: mysql:8.4
    container_name: patient-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: patient_db
      MYSQL_USER: patient_user
      MYSQL_PASSWORD: patient_password
    ports:
      - "3307:3306"
    volumes:
      - patient_mysql_data:/var/lib/mysql
    networks:
      - hospital-network
    restart: unless-stopped

  # ─── SERVICES ────────────────────────────────────────────
  patient-service:
    build:
      context: ./patient-service
    container_name: patient-service
    ports:
      - "3001:3001"
    environment:
      DB_HOST: patient-db
      DB_NAME: patient_db
      DB_USER: patient_user
      DB_PASSWORD: patient_password
    depends_on:
      - patient-db
    networks:
      - hospital-network
    restart: unless-stopped

  # ─── GATEWAYS ────────────────────────────────────────────
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      PATIENT_SERVICE_URL: http://host.docker.internal:3001
      DOCTOR_SERVICE_URL: http://host.docker.internal:3002
      APPOINTMENT_SERVICE_URL: http://appointment-service:3003
      RECORD_SERVICE_URL: http://medical-record-service:3004 #
    depends_on:
      - patient-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - hospital-network
    restart: unless-stopped

  graphql-gateway:
    build:
      context: ./graphql-gateway
    container_name: graphql-gateway
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      PATIENT_SERVICE_URL: http://host.docker.internal:3001
      DOCTOR_SERVICE_URL: http://host.docker.internal:3002
      APPOINTMENT_SERVICE_URL: http://appointment-service:3003
      RECORD_SERVICE_URL: http://medical-record-service:3004 #
    depends_on:
      - patient-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - hospital-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: api-gateway-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-gateway
      - graphql-gateway
    networks:
      - hospital-network
    restart: unless-stopped

networks:
  hospital-network:
    driver: bridge

volumes:
  patient_mysql_data:
